CFLAGS = -Wall -Wextra -O2 -std=c11 -pedantic -g `pkg-config --cflags freetype2`
CC = gcc
INCLUDES = -I/usr/include/freetype2
ALL_OBJS = main.o pty.o config.o

TARGETS = elterm

LIBS = -lutil -lX11 -lXft

elterm: $(ALL_OBJS)
	$(CC) $(LDFLAGS) $(CFLAGS) -o $@ $(LIBS) $(ALL_OBJS) 

clean:
	rm -f -- $(ALL_OBJS) $(TARGETS)

# autogenerated
main.o: main.c
pty.o: pty.c pty.h config.h
config.o: config.c config.h
